name: "CI: Lint and test"

on:
  workflow_call:
    secrets:
      TOKEN_ENCRYPTION_KEY:
        required: true
      TOKEN_SIGNING_KEY:
        required: true
      RESEND_API_KEY:
        required: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-lint-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-lint-
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 22
      - run: pnpm lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-test-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-test-
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 22
      - name: Configure .dev.vars
        run: |
          cat <<EOF > apps/api/.dev.vars
          TOKEN_ENCRYPTION_KEY=${{ secrets.TOKEN_ENCRYPTION_KEY }}
          TOKEN_SIGNING_KEY=${{ secrets.TOKEN_SIGNING_KEY }}
          RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
          EOF
      - run: |
          pnpm test
        env:
          TEST_DEV_VARS: ${{ secrets.TEST_DEV_VARS }}
