name: Deploy

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 22
      - name: Deploy to environment
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            pnpm turbo deploy -- -e prod
          else
            pnpm turbo deploy -- -e dev
          fi
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
          CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}
